# Structured arrays

https://docs.scipy.org/doc/numpy/user/basics.rec.html#structured-arrays

## 1. Introduction

In [2]:
import numpy as np
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [3]:
x[1]

('Fido', 3, 27.)

In [4]:
x['age']

array([9, 3], dtype=int32)

In [5]:
x['age'] = 5
x

array([('Rex', 5, 81.), ('Fido', 5, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

## 2. Structured Datatypes

### 2.1 Structured Datatype Creation

(1) A list of tuples, one tuple per field

In [6]:
np.dtype([('x', 'f4'), ('y', np.float32), ('z', 'f4', (2, 2))])

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

In [7]:
np.dtype([('x', 'f4'), ('', 'i4'), ('z', 'i8')])

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

(2) A string of comma-separated dtype specifications

In [8]:
np.dtype('i8, f4, S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [9]:
np.dtype('3int8, float32, (2,3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

(3) A dictionary of field parameter arrays

In [10]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [11]:
np.dtype({'names': ['col1', 'col2'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})

dtype({'names':['col1','col2'], 'formats':['<i4','<f4'], 'offsets':[0,4], 'itemsize':12})

(4) A dictionary of field names (old and discouraged)

In [12]:
np.dtype({'col1': ('i1', 0), 'col2': ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

### 2.2 Manipulating and Displaying Structured Datatypes

In [13]:
d = np.dtype([('x', 'i8'), ('y', 'f4')])
d.names

('x', 'y')

In [14]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

### 2.3 Automatic Byte Offsets and Alignment

In [15]:
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize", d.itemsize)
    
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2'))

offsets: [0, 1, 2, 6, 7, 15]
itemsize 17


In [16]:
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2', align=True))

offsets: [0, 1, 4, 8, 16, 24]
itemsize 32


### 2.4 Field Titles

In [20]:
np.dtype([(('my title', 'name'), 'f4')])

dtype([(('my title', 'name'), '<f4')])

In [21]:
np.dtype({'name': ('i4', 0, 'my title')})

dtype([(('my title', 'name'), '<i4')])

In [23]:
for name in d.names:
    print(d.fields[name][:2])

(dtype('int64'), 0)
(dtype('float32'), 8)


### 2.5 Union types

## 3. Indexing and Assignment to Structured Arrays

### 3.1 Assigning data to a Structured Array

(1) Assignment from Python Native Types (Tuples)

In [24]:
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8,f4,f8')
x[1] = (7, 8, 9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

(2) Assignment from Scalars

In [25]:
x = np.zeros(2, dtype='i8,f4,?,S1')
x

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [28]:
x[:] = 3
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [29]:
x[:] = np.arange(2)
x

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [31]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])
onefield = np.zeros(2, dtype=[('A', 'i4')])
nostruct = np.zeros(2, dtype='i4')
nostruct[:] = twofield

ValueError: Can't cast from structure to non-structure, except if the structure only has a single field.

In [32]:
nostruct[:] = onefield
nostruct

array([0, 0], dtype=int32)

(3) Assignment from other Structured Arrays

In [34]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])
b[:] = a
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

(4) Assignment involving subarrays

### 3.2 Indexing Structured Arrays

(1) Accessing Individual Fields

In [37]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])
x['foo']

array([1, 3])

In [38]:
x['foo'] = 10
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [40]:
y = x['bar']
y[:] = 5
x

array([(10, 5.), (10, 5.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [41]:
y.dtype, y.shape, y.strides

(dtype('float32'), (2,), (12,))

(2) Accessing Multiple Fields.

**Warning: The behavior of multi-field indexes will change from NumPy 1.14 to NumPy 1.15.**

In [42]:
# In Numpy 1.14,
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'i4')])
a[['a', 'c']]

array([(0, 0), (0, 0), (0, 0)], dtype=[('a', '<i4'), ('c', '<i4')])

In Numpy 1.15,

```python
>>> a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
>>> a[['a', 'c']]
array([(0, 0.), (0, 0.), (0, 0.)],
     dtype={'names':['a','c'], 'formats':['<i4','<f4'], 'offsets':[0,8], 'itemsize':12})

>>> a[['a','c']].view('i8')  # will fail in Numpy 1.15
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype
```

In [45]:
# Recommended fix in Numpy 1.14 and 1.15.
from numpy.lib.recfunctions import repack_fields
repack_fields(a[['a', 'c']]).view('i8')

/home/renwei/anaconda3/envs/ml/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.15 because this will return a view instead of a copy -- see release notes for details.
  app.launch_new_instance()


array([0, 0, 0])

In [46]:
a[['a', 'c']] = (2, 3)
a

array([(2, 0, 3), (2, 0, 3), (2, 0, 3)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

In [48]:
a[['a', 'c']] = a[['c', 'a']]
a

array([(3, 0, 2), (3, 0, 2), (3, 0, 2)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

### 3.3 Indexing with an integer to get a Structured Scalar

In [49]:
x = np.array([(1, 2., 3.)], dtype='i,f,f')
scalar = x[0]
scalar

(1, 2., 3.)

In [50]:
type(scalar)

numpy.void

In [52]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])
s = x[0]
s['bar'] = 100
x

array([(1, 100.), (3,   4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [53]:
scalar = np.array([(1, 2., 3.)], dtype='i, f, f')[0]
scalar[0]

1

In [54]:
scalar[1] = 4
scalar

(1, 4., 3.)

In [55]:
scalar.item(), type(scalar.item())

((1, 4.0, 3.0), tuple)

## 4. Viewing Structured Arrays Containing Objects

In order to prevent clobbering object pointers in fields of `numpy.object` type, numpy currently does not allow views of structured arrays containing objects.

## 5. Structure Comparison

In [56]:
a = np.zeros(2, dtype=[('a', 'i4'), ('b', 'i4')])
b = np.ones(2, dtype=[('a', 'i4'), ('b', 'i4')])
a == b

array([False, False])

In [57]:
b = np.ones(2, dtype=[('a', 'i4'), ('b', 'f4')])
a == b

/home/renwei/anaconda3/envs/ml/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  from ipykernel import kernelapp as app


False

In [58]:
b = np.ones(3, dtype=[('a', 'i4'), ('b', 'f4')])
a == b

/home/renwei/anaconda3/envs/ml/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  from ipykernel import kernelapp as app


False

## 6. Record Arrays

In [59]:
recordarr = np.rec.array([(1, 2., 'Hello'), (2, 3., 'World')],
                         dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
recordarr.bar

array([2., 3.], dtype=float32)

In [60]:
recordarr[1:2]

rec.array([(2, 3., b'World')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [61]:
recordarr[1:2].foo

array([2], dtype=int32)

In [63]:
recordarr.foo[1:2]

array([2], dtype=int32)

In [64]:
recordarr[1].baz

b'World'

In [67]:
arr = np.array([(1, 2., 'Hello'), (2, 3., 'World')],
            dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
recordarr = np.rec.array(arr)
recordarr

rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [73]:
arr = np.array([(1, 2., 'Hello'), (2, 3., 'World')],
               dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
recordarr = arr.view(np.recarray)
recordarr

rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [74]:
recordarr.dtype

dtype((numpy.record, [('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]))

In [76]:
arr2 = recordarr.view(recordarr.dtype.fields or recordarr.dtype, np.ndarray)
arr2

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [77]:
type(arr2)

numpy.ndarray

In [78]:
recordarr = np.rec.array([('Hello', (1, 2)), ('World', (3, 4))],
                         dtype = [('foo', 'S6'), ('bar', [('A', int), ('B', int)])])
type(recordarr.foo)

numpy.ndarray

In [79]:
type(recordarr.bar)

numpy.recarray